# Generated by Django 4.2.23 on 2025-08-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=30, unique=True, verbose_name="用户名"),
                ),
                ("password_MD5", models.CharField(max_length=100, verbose_name="密码")),
                ("avatar", models.CharField(max_length=100, verbose_name="头像")),
                ("real_name", models.CharField(max_length=30, verbose_name="真名")),
                ("students_id", models.CharField(max_length=30, verbose_name="学号")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "普通用户"), (1, "编辑"), (2, "管理员"), (3, "超级管理员")],
                        default=0,
                        help_text="●0(00)：一般用户 1(01)：编辑 2(10)：管理员 3(11)：兼任两者",
                        verbose_name="权限位",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户管理",
                "db_table": "user_info",
                "ordering": [
                    models.Index(fields=["created_at"], name="idx_created_at"),
                    models.Index(fields=["updated_at"], name="idx_updated_at"),
                    models.Index(fields=["students_id"], name="idx_students_id"),
                    models.Index(fields=["real_name"], name="idx_real_name"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("short_title", models.CharField(max_length=100, verbose_name="短标题")),
                ("link", models.TextField(verbose_name="链接")),
                ("content", models.TextField(verbose_name="详细内容")),
                ("deadline", models.DateTimeField(verbose_name="截止时间")),
                ("image_list", models.TextField(default=0, verbose_name="图片list")),
                ("published_time", models.DateTimeField(verbose_name="发布时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("reviewed", "已审核"),
                            ("rejected", "已拒绝"),
                            ("published", "已发布"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="类型")),
                ("tag", models.TextField(default="", verbose_name="标签")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_content",
                        to="django_models.user_info",
                    ),
                ),
                (
                    "describer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="described_content",
                        to="django_models.user_info",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content",
                        to="django_models.user_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章管理",
                "db_table": "content_management",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="django_models.user_info",
                    ),
                ),
                (
                    "news_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="django_models.content",
                    ),
                ),
                (
                    "parent_comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="django_models.comment",
                        verbose_name="父级评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论管理",
                "db_table": "comment",
                "ordering": [
                    models.Index(fields=["creator"], name="idx_creator_id"),
                    models.Index(fields=["news_id"], name="idx_news_id"),
                    models.Index(fields=["created_at"], name="idx_created"),
                    models.Index(
                        fields=["parent_comment_id"], name="idx_parent_comment_id"
                    ),
                    models.Index(fields=["updated_at"], name="idx_updated_at"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["creator"], name="idx_creator_id"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["describer"], name="idx_describer_id"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["reviewer"], name="idx_reviewer_id"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["type"], name="idx_type"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["deadline"], name="idx_deadline"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["published_time"], name="idx_publish_at"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["created_at"], name="idx_created_at"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["updated_at"], name="idx_updated_at"),
        ),
    ]
